menu:
  Home: /
  Archives: /archives
  About: /about/

weibo: https://www.test.com
github: https://www.test.com
linkedin: https://www.test.com
email: mailto:905980546@qq.com

#Put in /source
avator: 66.PNG