menu:
  Home: /
  Archives: /archives
  About: /about/
#If you dont want it, just comment it out
weibo: yourweibo
github: yourgithub
linkedin: yourlinkedin
email: mailto:youremail

#Put in /source
avator: avator.jpg
